version = 0.1

[default.deploy.parameters]
stack_name = "practicesolution-cognito"
resolve_s3 = true
s3_prefix = "practicesolution-cognito"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Env=\"dev\" S3BucketName=\"practice-solution\" CognitoUserPoolName=\"practicesolution-userpool\" CognitoWebClientName=\"practicesolution-webclient\""
image_repositories = []
